### PR TITLE
Fix downloading of install when running update

### PR DESCRIPTION
**Pull request by Kurounin**
Fix downloading of install. Set correct permissions of downloaded file and remove it after installing.

### CODE REVIEW

**Comment by jwineman** [comment]
Was this blocking the plugin's installation on your cPanel instance?

**Comment by Kurounin** [comment]
Yes, on Cloudlinux 6.7 when running the update.sh curl would only display the content of the cloudflare.install.sh file instead of saving it.

**Comment by jwineman** [comment]
Hi @Kurounin,

Denying this pull request because not contains merge conflicts (not your fault) and we're trying to release today.  Really appreciate your help though, we've included your fix as part of https://github.com/cloudflare/CloudFlare-CPanel/pull/109.

Thanks,
John

**Comment by jwineman** [comment]
https://github.com/cloudflare/CloudFlare-CPanel/releases/tag/v6.0.6

**Pull request closed without merging**
