### PR TITLE
PI-940 Add "SSL Settings" to  moresettings/security

### PR DESCRIPTION
**Pull request by thellimist**

### CODE REVIEW

**Comment by jwineman** [comment]
What ticket is this associated with?  Didn't we remove the SSLCard because of the certificate issues cPanel servers often face?

**Comment by jwineman** [comment]
This is fine because we have CNAME SSL certs which fixes the issue that caused us to remove the card in the first place.  PI-940

**Comment by jwineman** [comment]
@thellimist whats the status on this?  It will conflict with @manatarms PR after he merges.

**Comment by thellimist** [comment]
I forgot about this. Merged it

**Pull request merged**
