### PR TITLE
Update cloudflare_update.sh

### PR DESCRIPTION
**Pull request by uncleVALERA**

### CODE REVIEW

**Comment by jwineman** [comment]
Hi,

Can you provide some context around this PR?  Is it fixing an issue you were having?  If so can you provide the OS, version of cPanel and steps to reproduce?

Thanks,
John

**Comment by uncleVALERA** [comment]
I have seen in #104 already was solved the issue.
--
CloudLinux Server release 6.8
cPanel 58.0  (build 20)

**Comment by jwineman** [comment]
Can you describe the issue you're experiencing?  That PR is also lacking detail so I'm trying to figure out what you guys are trying to fix here.  What went wrong?

**Comment by uncleVALERA** [comment]
Old script cloudflare_update.sh did not update plugin.
New script have downloaded cloudflare.install.sh but didn't save it and have printed him to console.
curl -s -k -L "https://raw.githubusercontent.com/cloudflare/CloudFlare-CPanel/master/cloudflare.install.sh" > cloudflare.install.sh

After solved this issue script cloudflare.install.sh was saved but didn't execute.
chmod +x cloudflare.install.sh

After the fix plugin has updated.
P.S. Sorry for my English

**Comment by jwineman** [comment]
Hi @uncleVALERA,

Thanks for providing the extra information, this has been very helpful in helping us determine the root cause!  I'm going to close this as a duplicate of https://github.com/cloudflare/CloudFlare-CPanel/pull/104 but we do plan on incorporating your changes in the next release!

Thanks,
John

**Comment by jwineman** [comment]
Fixed https://github.com/cloudflare/CloudFlare-CPanel/pull/109

**Comment by jwineman** [comment]
https://github.com/cloudflare/CloudFlare-CPanel/releases/tag/v6.0.6

**Pull request closed without merging**
